"""RouteMate: deterministic journey compatibility, routing abstraction, and batch assignment."""

from .models import Coordinate, Journey, Vehicle, VerificationContext
from .geometry import haversine_km, polyline_length_km, route_similarity, direction_similarity
from .scoring import compatibility_score, CompatibilityResult
from .assignment import (
    run_assignment,
    build_feasibility_graph,
    assign_greedy,
    assign_auction,
    assign_optimal,
    compute_optimality_gap,
    AssignmentResult,
    AssignmentGroup,
    MatchEdge,
)
from .routing import (
    RouteQuery,
    RouteResult,
    RoutingProvider,
    DeterministicGeometricRouter,
    MockRoutingProvider,
    RoadNetwork,
    NetworkGraphRouter,
    create_urban_grid_network,
    create_osm_sf_downtown_network,
    compute_road_detour,
    RoadDetourResult,
    OSRMClientRouter,
    RoutingError,
    RouteNotFoundError,
    ProviderUnavailableError,
    InvalidQueryError,
)
from .road_benchmark import (
    RouteComparisonPoint,
    DetourComparisonPoint,
    RoadBenchmarkReport,
    run_road_network_benchmark,
)
from .road_network_validation import (
    CandidateTripFeatures,
    RankingMetrics,
    DisagreementAnalysis,
    Experiment008Report,
    run_road_network_validation_experiment,
)
from .hybrid_pruning import (
    CircuityCalibration,
    PruningEvaluationMetrics,
    StressScaleResult,
    Experiment009Report,
    calibrate_circuity_bounds,
    pruner_no_pruning,
    pruner_fixed_euclidean,
    pruner_circuity_aware,
    pruner_two_stage_geometric,
    pruner_admissible_lower_bound,
    run_experiment_009,
)
from .congestion import (
    BPRParameters,
    BPRCongestionModel,
    TimeDependentRouteResult,
    TimeDependentRouter,
    DynamicDetourResult,
)
from .dynamic_congestion import (
    DynamicCandidateFeatures,
    CongestionScenarioMetrics,
    TimeWindowSensitivityResult,
    DynamicPruningEvaluation,
    DynamicScalingResult,
    Experiment010Report,
    run_experiment_010,
)
from .multi_rider_pooling import (
    StopNode,
    MultiRiderRouteResult,
    ExactSolverResult,
    CapacityComparisonResult,
    CongestionStopOrderShift,
    SolverOptimalityComparison,
    MultiRiderPruningMetrics,
    Experiment011Report,
    validate_stop_sequence,
    generate_valid_stop_sequences,
    evaluate_stop_sequence_dynamic,
    solve_multi_rider_exact,
    solve_multi_rider_greedy_insertion,
    is_multi_rider_subset_admissible,
    run_experiment_011,
    save_experiment_011_outputs,
)
from .recourse import (
    IncidentEvent,
    StochasticDwellModel,
    IncidentAwareRouter,
    RecourseTripEvaluation,
    RecourseScenarioMetrics,
    Experiment012Report,
    build_incident_scenarios,
    evaluate_trip_recourse,
    run_experiment_012,
    save_experiment_012_outputs,
)
from .rolling_dispatch import (
    RequestStatus,
    DispatchRiderRequest,
    RouteStop,
    DispatchVehicle,
    PolicyRunMetrics,
    DemandRegimeComparison,
    Experiment013Report,
    generate_synthetic_dispatch_requests,
    FleetDispatchSimulator,
    run_experiment_013,
    save_experiment_013_outputs,
)
from .synthesis import (
    ExperimentAuditRecord,
    HypothesisEvaluationRecord,
    TradeoffAnalysisRecord,
    SynthesisReport,
    EXPERIMENT_METADATA_REGISTRY,
    audit_repository_experiments,
    compile_hypothesis_evaluations,
    compile_tradeoff_analyses,
    compile_threats_to_validity,
    run_experiment_014,
    save_experiment_014_outputs,
)

__all__ = [
    "Coordinate", "Journey", "Vehicle", "VerificationContext",
    "haversine_km", "polyline_length_km", "route_similarity",
    "direction_similarity", "compatibility_score", "CompatibilityResult",
    "run_assignment", "build_feasibility_graph", "assign_greedy", "assign_auction",
    "assign_optimal", "compute_optimality_gap",
    "AssignmentResult", "AssignmentGroup", "MatchEdge",
    "RouteQuery", "RouteResult", "RoutingProvider",
    "DeterministicGeometricRouter", "MockRoutingProvider",
    "RoadNetwork", "NetworkGraphRouter", "create_urban_grid_network",
    "create_osm_sf_downtown_network",
    "compute_road_detour", "RoadDetourResult", "OSRMClientRouter",
    "RoutingError", "RouteNotFoundError", "ProviderUnavailableError", "InvalidQueryError",
    "RouteComparisonPoint", "DetourComparisonPoint", "RoadBenchmarkReport", "run_road_network_benchmark",
    "CandidateTripFeatures", "RankingMetrics", "DisagreementAnalysis", "Experiment008Report",
    "run_road_network_validation_experiment",
    "CircuityCalibration", "PruningEvaluationMetrics", "StressScaleResult", "Experiment009Report",
    "calibrate_circuity_bounds", "pruner_no_pruning", "pruner_fixed_euclidean", "pruner_circuity_aware",
    "pruner_two_stage_geometric", "pruner_admissible_lower_bound", "run_experiment_009",
    "BPRParameters", "BPRCongestionModel", "TimeDependentRouteResult", "TimeDependentRouter",
    "DynamicDetourResult", "DynamicCandidateFeatures", "CongestionScenarioMetrics",
    "TimeWindowSensitivityResult", "DynamicPruningEvaluation", "DynamicScalingResult",
    "Experiment010Report", "run_experiment_010",
    "StopNode", "MultiRiderRouteResult", "ExactSolverResult", "CapacityComparisonResult", "CongestionStopOrderShift",
    "SolverOptimalityComparison", "MultiRiderPruningMetrics", "Experiment011Report",
    "validate_stop_sequence", "generate_valid_stop_sequences", "evaluate_stop_sequence_dynamic",
    "solve_multi_rider_exact", "solve_multi_rider_greedy_insertion",
    "is_multi_rider_subset_admissible", "run_experiment_011", "save_experiment_011_outputs",
    "IncidentEvent", "StochasticDwellModel", "IncidentAwareRouter", "RecourseTripEvaluation",
    "RecourseScenarioMetrics", "Experiment012Report", "build_incident_scenarios",
    "evaluate_trip_recourse", "run_experiment_012", "save_experiment_012_outputs",
    "RequestStatus", "DispatchRiderRequest", "RouteStop", "DispatchVehicle",
    "PolicyRunMetrics", "DemandRegimeComparison", "Experiment013Report",
    "generate_synthetic_dispatch_requests", "FleetDispatchSimulator",
    "run_experiment_013", "save_experiment_013_outputs",
    "ExperimentAuditRecord", "HypothesisEvaluationRecord", "TradeoffAnalysisRecord",
    "SynthesisReport", "EXPERIMENT_METADATA_REGISTRY", "audit_repository_experiments",
    "compile_hypothesis_evaluations", "compile_tradeoff_analyses", "compile_threats_to_validity",
    "run_experiment_014", "save_experiment_014_outputs",
]


